### ISSUE TITLE
[Feature] As a developer, I want to use the FragmentExtension

### ISSUE THREAD

**Issue by lydiasama** [nimblehq/android-common-ktx#1]
## Why

Kotlin provides the ability to extend a class with new functionality without having to inherit from the class or use design patterns such as Decorator. This is done via special declarations called extensions.

## Acceptance Criteria
Add the useful extensions from the Fragment class for using:
- [ ] setWindowStyle to show fullscreen (hide status bar background), Check/Request Permission
- [ ] Add Unit Test
 
## Who Benefits?
Android developers

**Comment by luongvo** [comment]
@hoangnguyen92dn @lydiasama I don't think we need this support anymore 🙏

**Comment by hoangnguyen92dn** [comment]
Close this since we don't use Fragment in modern Android development
